### ISSUE TITLE
DB Persistence

### ISSUE THREAD

**Issue by DominikBaer** [ibm-ecm/container-demo#1]
Hi
I am wondering whether it would make sense to add following functionality:
-DB Persistency
-Filesystem Persistency using Docker Volume for the Filestore
-Start & Stop Scripts

I have implemented DB2 persistency using following approach:

VOLUME_NAME='ecm-db2-data-home'
# Checking if docker container with $CONTAINER_NAME name exists.
COUNT=$(docker volume ls | grep "$VOLUME_NAME" | wc -l)
if (($COUNT > 0)); then
    echo 'volume '$VOLUME_NAME 'exists'
else
        echo 'create volume '$VOLUME_NAME
        sudo docker volume create $VOLUME_NAME
fi

CONTAINER_NAME='ecmdb'
# Checking if docker container with $CONTAINER_NAME name exists.
COUNT=$(docker ps -a | grep "$CONTAINER_NAME" | wc -l)
if (($COUNT > 0)); then
    echo 'container '$CONTAINER_NAME 'exists'
else
        echo 'starting container '$CONTAINER_NAME        
        sudo docker run \
        	--name ecmdb -d -p 50000:50000 -e DB2INST1_PASSWORD=Password01 \
			-e LICENSE=accept   \
			-v  ecm-db2-data-home:/home  \
			ecmdb2express \
			db2start
fi

**Comment by abrakhan** [comment]
@DominikBaer ,
Thank you for your feedback.
We will look into implementing this in the next version.

-Abrar
