### ISSUE TITLE
DB2_IMAGE_TAG overriding

### ISSUE THREAD

**Issue by ozimakov** [ibm-ecm/container-demo#10]
Script etProperties.sh has dublicate DB2_IMAGE_TAG variable definition.
So, if user change the value on the top, it will overrided by the value below, so older version will be required by other scripts, including gatherHostInfo.sh container availability check.

**Comment by abrakhan** [comment]
@ozimakov - The duplicate parameters have been removed and a new version has been uploaded.
Thank you for your feedback.
