### ISSUE TITLE
any chance to opensource GA com.ibm.CETools?

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-demo#11]
Hi, any chance IBM can GA or opne source the CE tool: com.ibm.CETools
Would help with OS and GCD creation.

**Comment by abrakhan** [comment]
@TiloGit - CETools is part of a wrapper utility that calls the Content Platform Engine Java APIs for GCD/Object Store creation and configuration. 
You can get additional info about these APIs in the Knowledge Center: 
https://www.ibm.com/support/knowledgecenter/SSNW2F_5.5.0/com.ibm.p8.ce.dev.java.doc/overview-summary.html

-Abrar
