### ISSUE TITLE
Error in deployCPE.sh - FNRCE0040E: E_NOT_AUTHENTICATED: The user is not authenticated

### ISSUE THREAD

**Issue by cocodrilo-emplumado** [ibm-ecm/container-demo#12]
Is giving this error when running the createP8Domain.sh, and if I check the CPE container log is adding my GLOBAL_PASSWORD=passw0rd variable as hostname:

 CWIML4520E: The LDAP operation could not be completed. The LDAP naming exception javax.naming.CommunicationException: **passw0rd**:389 [Root excepti
on is java.net.UnknownHostException: passw0rd] occurred during processing.

Please advise.

**Comment by abrakhan** [comment]
@cocodrilo-emplumado - Please try the following steps:
1. Check the HOST_NAME parameter value in the file - setProperties.sh. Make sure the hostname value can be resolved locally. Update value if necessary.
2. View the log file - cpit_log.log. Check for any errors that occurred before this exception.
3. Edit the file - install-scripts/status.log. Set the following value:
     deployCPE: NotCompleted 
4. Re-run the install script - cpit.sh.

If the error still persists, please send me the log file - cpit_log.log

-Abrar

**Comment by cocodrilo-emplumado** [comment]
I was running out of time and what I did is added my GLOBAL_PASSWORD to hosts file in CPE and ICP containers someting like:

192.168.2.8      passw0rd

and I got it working, but still I need to find out the root cause.

This files 

Begin to set hostname to filenet:
  - Updated hostname for setProperties.sh
  - Updated hostname for /home/filenet/container-demo/Container-PIT/install-scripts/config-files/CPE/FNGCDDS.xml
  - Updated hostname for /home/filenet/container-demo/Container-PIT/install-scripts/config-files/CPE/OS1DB.xml
  - Updated hostname for /home/filenet/container-demo/Container-PIT/install-scripts/config-files/common/ldap.xml
  - Updated hostname for /home/filenet/container-demo/Container-PIT/install-scripts/config-files/ICN/ICNDS.xml

have serverName="**passw0rd**" so I'm guessing something in **updateConfigFiles.sh** is wrong but not sure yet, my guess is here:

function modifyLdapConfigFile(){
        if [ -f $ScriptsDir/config-files/common/$LDAP ];  then
                if [[ "Linux" = "$OS" ]]; then
                        sed -i -e "s/**filenet**/$GLOBAL_PASSWORD/g" $ScriptsDir/config-files/common/$LDAP
                elif [[ "Mac" = "$OS" ]]; then
                        sed -i "" -e "s/**filenet**/$GLOBAL_PASSWORD/g" $ScriptsDir/config-files/common/$LDAP
                fi
                echo "Updated ldap password in $ScriptsDir/config-files/common/$LDAP"
        else
                echo "Can not find $ScriptsDir/config-files/common/$LDAP!"
                exit_script
        fi
}

As filenet is my hostname is changing it for passw0rd. I'll try other hostname


Best regards!

**Comment by abrakhan** [comment]
The default password in the config files is "filenet". So if your hostname is also the same it will get replaced by the scripts. We will look into resolving this in the next release.

-Abrar

**Comment by jmalyik** [comment]
I got this error when for some reason my ldap host was down, so I would recommend to check the status fo the containers.

**Comment by abrakhan** [comment]
Resolved
