### ISSUE TITLE
Request; add source code here

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-demo#13]
Hi, 

would be great if you can add the source code here beside just the ZIP file. 
That way we can better track changes (like change of

> -u 50001 (since CPE 553)
> -e JVM_CUSTOMIZE_OPTIONS=-DFileNet.WSI.AutoDetectLTPAToken=true (since CPE554)

Hope you can make this happen. 

Thanks
Tilo

**Comment by abrakhan** [comment]
Please contact your IBM Account team for access to the source code.
