### ISSUE TITLE
Ubuntu 20.04 incompatibility due to the unavailable python 2

### ISSUE THREAD

**Issue by jmalyik** [ibm-ecm/container-demo#14]
However In ubuntu 20.04 LTS the python 2 is still available in some extent, but the pip is not and this causes various errors during the navigator related operations (it is not possible to fetch the used python modules).

**Comment by abrakhan** [comment]
@jmalyik - The Container PIT utility has not been qualified with Ubuntu 20.x. This will be done in the next release of the utility.

**Comment by abrakhan** [comment]
Python3 support has been added to the Q2 2020 release.
