### ISSUE TITLE
How do we deploy GraphQL container with this container-demo

### ISSUE THREAD

**Issue by SKKOVVURI** [ibm-ecm/container-demo#16]
HI,

Thanks for the all-in-one demo containers set. I was able to successfully deploy all containers. But I want to know how to deploy the GraphQL container to work with this demo environment. Sorry, I had to post this question here as an issue although it's not part of the demo. Some pointers and manual workaround suggestions will help.

Thanks,
Sai

**Comment by abrakhan** [comment]
Please refer to this repository: https://github.com/ibm-ecm/container-samples

-Abrar
