### ISSUE TITLE
ACCE/Navigator Console logs out in less than 30 seconds

### ISSUE THREAD

**Issue by apaeslab** [ibm-ecm/container-demo#19]
Hi, I have installed ECM environment using this scripts and everything works ok however, after accessing the console (both navigator and ACCE) it times out after less than 30 seconds and I have to log back in.

Could you pls inform how to fix this issue ?

Thanks, Andre

**Comment by lpchitta** [comment]
Hello, Thank you for reaching out to us. This is not actively monitored github which is why this is delayed.
Can you open a support case so that our support will look at this to address the issue ?

**Comment by lpchitta** [comment]
We will close the git issue as you will require to open a support case to get assitence.
