### ISSUE TITLE
Pull Request welcome?

### ISSUE THREAD

**Issue by mod242** [ibm-ecm/container-demo#24]
Thanks for providing this excellent Toolset, it helps a lot in trying out Demo-Cases locally.

I made some enhancements for myself and wanted to ask whether you would be interrested in an Pull Request to contribute these changes. In Detail I made the following enhancements:
- Possibility to optional download the Docker Images from cp.icr.io (or another local registry), settable via an extra paramater in setproperties
- Upgrade to recent Versions of FileNet CPE 5.5.8 and ICN 3.0.11
- Refactoring of check of requirements
- Implementation to use Postgresql instead of DB2 (settable via parameter in setproperties)

If a pull request is welcome I will create one, if not, just close this issue.

**Comment by abrakhan** [comment]
Hi @mod242 

This deployment utility has been deprecated and is no longer supported.
You can use these scripts for your deployment:
IBM Cloud Pak for Business Automation 22.0.1 - Starter deployment
https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=deployment-installing-starter-by-running-scripts

**Comment by TiloGit** [comment]
@mod242 let me know your GH repository. Would love to see simple demo option being available bit longer.
