### ISSUE TITLE
CPE 558 and ICN 3011 release planned? 

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-demo#25]
Hi, 

any plans for CPE 558 and ICN 3011 (LTSR release) or even the latest CPE 559? ICN 3.0.12?

**Comment by abrakhan** [comment]
Hi @TiloGit 

This deployment utility has been deprecated and is no longer supported.
Please use the IBM Cloud Pak for Business Automation 22.0.1 Starter Deployment scripts:
https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=deployments-installing-starter-deployment-by-running-scripts
