### ISSUE TITLE
Tar File Names in setProperties.sh are not like GA

### ISSUE THREAD

**Issue by DominikBaer** [ibm-ecm/container-demo#4]
I would adapt the tar file names accordingly to GA Names.
IBM_FILENET_CONTENT_PLATFORM_ENGI.tar
IBM_CONTENT_NAVIGATOR_V3.0.4_LINU.tar

**Comment by DominikBaer** [comment]
I had some issues after cloned your zip file. Looks like the shell scripts had windows style endings.
dos2unix *.sh helped

**Comment by abrakhan** [comment]
@DominikBaer ,
Thank you for your feedback.
We will look into implementing this in the next version.

-Abrar

**Comment by abrakhan** [comment]
Fixed on Jul 10 2018
