### ISSUE TITLE
Connectivity

### ISSUE THREAD

**Issue by DominikBaer** [ibm-ecm/container-demo#6]
I have installed the whole approach in an Ubuntu VM.
It looks like the communication breaks between docker containers when using hostname.
I have not yet had enough time to investigate but if I am using the IP-Adress I can ping from one container to the other. When I use the hostname for communication from the setProperties.sh it doesn't. So it is clear that the installation breaks at the point of P8Domain creation.
Having manually overwritten the IP-adress in the ldap.xml file, I can login to acce. So it seems to be a true dns problem on the box.
I guess we should use either a -link parameter in the docker startup command or specifying the network.

**Comment by DominikBaer** [comment]
I solved it by adding 

sudo docker network create cm551

and then added in each container start --network cm551

**Comment by abrakhan** [comment]
Will need to do some investigation for this issue.

-Abrar

**Comment by DominikBaer** [comment]
Abrar

not sure whether it makes a difference but I guess you tested mainly on mac.
I have a vmware ubuntu guest os with NAT (dhcp outside and inside) interface.
By default dns names of docker containers are only visible for the container. In some areas you are using the docker_host in other the hostname of the other container.
If you are using the privileged settings
you can workaround but this is ugly.
My conclusion is to use a docker network and to connect on container names (cpe, ldap, db2). So you don't need the hostname or you are setting it to the same as the container name.
I am almost done now - expect to reach a successful deployment by eob today.

cheers


Von meinem iPhone gesendet

**Comment by DominikBaer** [comment]
I had to update in a few locations the $Host_Name with $CPE_CONTAINER_LOCATION
In nearly all configuration files the generated dbserver, cpeserver, ldapserver target was pointing to the $Host_Name instead of the container name. It will take a few time to update all scripts to reflect that correctly. The os creation script I was not able to run over the jdk container. I had run the code from the command line. Need to see what is going wrong there. Probalby the 2 last parameters were missing in the first call.

**Comment by DominikBaer** [comment]
System is now up and running.....

**Comment by abrakhan** [comment]
Your network configuration seems to quite unique.
We do have the resources to replicate your environment in our development labs.

**Comment by abrakhan** [comment]
@DominikBaer - We have included the "--add-host" parameter to the "docker run" commands for all containers. This should resolve the name resolution issue from inside the containers. These changes are in the latest version of the Container-PIT.zip.

**Comment by DominikBaer** [comment]
Abrar

 

Now it is working like a charm.

 

Thanks

 

Dominik

 

--
