### ISSUE TITLE
CreateICN Desktop

### ISSUE THREAD

**Issue by DominikBaer** [ibm-ecm/container-demo#7]
the errorhandling in this particular step is not correct. I had problems with the connectivity but I got a message, saying the desktop and repository have been created. Which was not the case.
I guess either in the python code we need to check whether the call was really successful.

**Comment by RichardI2V** [comment]
Hi I am experiencing the same issue with the createICNDesktop.sh script. Does anyone have a fix for this ?

**Comment by abrakhan** [comment]
@RichardI2V - Can you provide some more details about the error?

**Comment by RichardI2V** [comment]
Hi Abrar,

I am running Ubuntu 18.04

I have run the cpit.sh and it errors every time on this section

createICNDesktop.sh was not run before, running now!
==========================================
Thu Sep  6 16:06:06 UTC 2018
Begining to create ICN desktop 'ECM' together with repository 'P8Repository'
/home/sysadmin/ecm/cpit/install-scripts/createICNDesktop.sh: line 18: python: command not found
sysadmin@ubuntup8:~/ecm/cpit$ cd install-scripts
sysadmin@ubuntup8:~/ecm/cpit/install-scripts$ sudo ./createICNDesktop.sh
[sudo] password for sysadmin:
==========================================
Thu Sep  6 16:11:39 UTC 2018
/home/sysadmin/ecm/cpit/install-scripts
Begining to create ICN desktop 'ECM' together with repository 'P8Repository'
./createICNDesktop.sh: line 18: python: command not found
Something wrong, stop and exit now.

Any help you can provide will be greatly appreciated

Regards,
Richard Slater

Insight 2 Value
+44 (0) 7801719342 (Mobile)

[linkedin]<https://uk.linkedin.com/in/richardslater>
www.insight2value.co.uk<http://insight2value.co.uk/>


Notice: Internet communications are not secure and therefore I do not accept legal responsibility for the contents of this message. Any views or opinions presented are solely those of the author.

**Comment by abrakhan** [comment]
@RichardI2V - The error is most likely because the Python packages are not installed in your environment. 
Try these commands to install Python:
# sudo apt-get install python-pip -y
# sudo pip install docker-py
# sudo apt-get update

Then re-launch the Container PIT using this command:
# sudo ./cpit.sh

-Abrar

**Comment by DominikBaer** [comment]
Hi Abrar

no - the installation is okay. The objectstore
was nor ready but I got the feedback that everything worked.

The python script emulates a user session. From my point of view a quirk. I would rather expect Productmanagement creating an API.

Cheers
Dominik


Von meinem iPhone gesendet

**Comment by RichardI2V** [comment]
Hi, 
Thanks for the help so far. I get another error now that I have managed to install Python and PIP


Fri Sep  7 08:38:16 UTC 2018
/home/sysadmin/ecm/cpit/install-scripts
Begining to create ICN desktop 'ECM' together with repository 'P8Repository'
Traceback (most recent call last):
  File "/home/sysadmin/ecm/cpit/install-scripts/../icnadmin/bin/icndefaultdriver.py", line 9, in <module>
    from navigator import Navigator
  File "/home/sysadmin/ecm/cpit/icnadmin/bin/navigator.py", line 6, in <module>
    import requests
ImportError: No module named requests
Something wrong, stop and exit now.
sysadmin@ubuntup8:~/ecm/cpit/install-scripts$
