### ISSUE TITLE
Issue with disk space check on MacOS

### ISSUE THREAD

**Issue by ozimakov** [ibm-ecm/container-demo#9]
Trying to run cpinit on MacOS Mojave (iMac 27" 2017). There's no "disk1", and this causes the problem. Main partition (mounted on root "/") is /dev/disk2s1.
So, gatherHostInfo.sh fails on
`avail_disk_space='df -h | grep "disk1" | awk '{ print $4 }' | head -1 | cut -f 1 -d "G" | sed 's/[[:space:]]//g''`
Changing disk1 on disk2 in command below fixes the problem.

**Comment by abrakhan** [comment]
@ozimakov - We will investigate the issue and look at having a fix for it in the next release.

-Abrar
